### ISSUE TITLE
Updating/work-with this template for GHA feature.

### ISSUE THREAD

**Issue by zedy-wj** [pamelafox/django-quiz-app#32]
We are updating this template to support new features in `Github Action`.

For the Github Action feature: We will remove two lines of code on container image and add GHA code after checkout step in the `.github/workflow/azure-dev.yml` file. (Shown as below)
<img width="302" alt="image" src="https://github.com/Azure-Samples/openai-plugin-fastapi/assets/81678720/b78e7045-08c4-4e09-90cd-ba0b22f50fe7">

@rajeshkamal5050 , @pamelafox for notification.

**Comment by pamelafox** [comment]
Fixed in #43
